### ISSUE TITLE
Fix `npm run dev`

### ISSUE THREAD

**Issue by jslopezgithub** [jslopezgithub/cnca#46]
**Describe the bug**
Running `npm run dev results in a crash`

**To Reproduce**
1. Go to the project
2. Run `npm run dev` from the command line
3. See the error ```[0] internal/modules/cjs/loader.js:638
[0]     throw err;
[0]     ^
[0]
[0] Error: Cannot find module '/Users/jslopez/Documents/workspace/cyf/cnca/Backend/server.js'
[0]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
[0]     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[0]     at startup (internal/bootstrap/node.js:283:19)
[0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
[0] [nodemon] app crashed - waiting for file changes before starting...```

**Expected behavior**
There should not be any warnings or crashes

**Comment by milleymilli** [comment]
we get this  error because we remove the server.js from the backend folder last time but now it's fixed
