### ISSUE TITLE
Failure running `npm run test`

### ISSUE THREAD

**Issue by jslopezgithub** [jslopezgithub/cnca#48]
**Describe the bug**
Running the tests result in no test found and an error. Perhaps we need a dummy test?

**To Reproduce**
1. Go to the cnca project
2. Run `npm run test` from the terminal
3. See the error
`npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cnca@1.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cnca@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Expected behavior**
The script should run properly

**Comment by jslopezgithub** [comment]
I'm getting this error when running it. The version of FSEvents in use, does not seem to have an available version on mac os.

[TypeError: fsevents is not a function
    at new FSEventsWatcher (/Users/jslopez/Documents/workspace/cyf/cnca/node_modules/jest-haste-map/build/lib/FSEventsWatcher.js:162:20)
    at createWatcher (/Users/jslopez/Documents/workspace/cyf/cnca/node_modules/jest-haste-map/build/index.js:1052:23)
    at Array.map (<anonymous>)
    at HasteMap._watch (/Users/jslopez/Documents/workspace/cyf/cnca/node_modules/jest-haste-map/build/index.js:1230:44)
    at /Users/jslopez/Documents/workspace/cyf/cnca/node_modules/jest-haste-map/build/index.js:517:21
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/jslopez/Documents/workspace/cyf/cnca/node_modules/jest-haste-map/build/index.js:193:24)
    at _next (/Users/jslopez/Documents/workspace/cyf/cnca/node_modules/jest-haste-map/build/index.js:213:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)](url)

**Comment by jslopezgithub** [comment]
The problem is only an issue on mac os that cannot install fsevents@1.2.11. As a workaround using 1.2.9 work
